"""Seller-facing category taxonomy for the Malaysia profit calculator.

TikTok's public Malaysia commission table defines the fee-bearing category
groups.  The calculator adds practical terminal choices below those groups so
operators can select a recognisable product type while every leaf still
inherits the rate of its official commission group.
"""


def group(label, rule_code, *children):
    return {"label": label, "rule_code": rule_code, "children": children}


def root(label, *children):
    return {"label": label, "children": children}


CATEGORY_TAXONOMY = (
    root(
        "箱包",
        group(
            "女包",
            "fashion-luggage-and-bags-women-s-bags",
            ("bag-womens-womens-backpacks", "女士双肩包"),
            ("bag-womens-womens-handbags", "女士手提包"),
            ("bag-womens-womens-tote-bags", "女士托特包"),
            ("bag-womens-womens-shoulder-bags", "女士单肩包"),
            ("bag-womens-crossbody-bags", "女士斜挎包"),
            ("bag-womens-womens-clutches-wristlets", "女士手拿包与腕包"),
            ("bag-womens-womens-chest-waist-bags", "女士胸包及腰包"),
            ("bag-womens-wallets", "女士钱包"),
            ("bag-womens-card-coin-purses", "女士卡包与零钱包"),
            ("bag-womens-key-pouches", "女士钥匙包"),
            ("bag-womens-phone-bags", "女士手机包"),
            ("bag-womens-evening-bags", "女士晚宴包"),
            ("bag-womens-briefcases", "女士公文包"),
            ("bag-womens-bag-sets", "女士包套装"),
            ("bag-womens-other", "其他女包"),
        ),
        group(
            "男包",
            "fashion-luggage-and-bags-men-s-bags",
            ("bag-mens-backpacks", "男士双肩包"),
            ("bag-mens-handbags", "男士手提包"),
            ("bag-mens-shoulder-bags", "男士单肩包"),
            ("bag-mens-crossbody-bags", "男士斜挎包"),
            ("bag-mens-chest-waist-bags", "男士胸包及腰包"),
            ("bag-mens-wallets", "男士钱包"),
            ("bag-mens-card-coin-purses", "男士卡包与零钱包"),
            ("bag-mens-briefcases", "男士公文包"),
            ("bag-mens-clutches", "男士手拿包"),
            ("bag-mens-phone-bags", "男士手机包"),
            ("bag-mens-bag-sets", "男士包套装"),
            ("bag-mens-other", "其他男包"),
        ),
        group(
            "旅行箱包",
            "fashion-luggage-and-bags-luggage-and-travel-bags",
            ("bag-travel-suitcases", "拉杆箱与旅行箱"),
            ("bag-travel-carry-on", "登机箱"),
            ("bag-travel-duffel", "旅行包与行李袋"),
            ("bag-travel-foldable", "折叠旅行包"),
            ("bag-travel-garment-bags", "西装袋"),
            ("bag-travel-packing-cubes", "旅行收纳袋"),
            ("bag-travel-toiletry-bags", "旅行洗漱包"),
            ("bag-travel-passport-covers", "护照夹"),
            ("bag-travel-luggage-tags", "行李牌"),
            ("bag-travel-luggage-straps", "行李绑带"),
            ("bag-travel-luggage-covers", "行李箱保护套"),
            ("bag-travel-accessory-sets", "旅行配件套装"),
        ),
        group(
            "功能箱包",
            "fashion-luggage-and-bags-functional-bags",
            ("bag-functional-laptop-bags", "电脑包"),
            ("bag-functional-camera-bags", "相机包"),
            ("bag-functional-diaper-bags", "妈咪包"),
            ("bag-functional-insulated-bags", "保温包"),
            ("bag-functional-lunch-bags", "午餐包"),
            ("bag-functional-tool-bags", "工具包"),
            ("bag-functional-sports-bags", "运动包"),
            ("bag-functional-gym-bags", "健身包"),
            ("bag-functional-outdoor-backpacks", "户外背包"),
            ("bag-functional-cycling-bags", "骑行包"),
            ("bag-functional-pet-carriers", "宠物外出包"),
            ("bag-functional-document-bags", "文件包"),
            ("bag-functional-shopping-bags", "购物袋"),
            ("bag-functional-waterproof-bags", "防水袋"),
            ("bag-functional-cosmetic-bags", "化妆包"),
            ("bag-functional-storage-bags", "收纳包"),
        ),
        group(
            "箱包配件",
            "fashion-luggage-and-bags-bag-accessories",
            ("bag-accessories-straps", "包带与肩带"),
            ("bag-accessories-chains", "包链"),
            ("bag-accessories-charms", "包挂件"),
            ("bag-accessories-hardware", "包扣与五金"),
            ("bag-accessories-organizers", "包内胆与内袋"),
            ("bag-accessories-base-shapers", "包底板与定型板"),
            ("bag-accessories-protective-covers", "箱包保护套"),
            ("bag-accessories-wallet-parts", "钱包配件"),
            ("bag-accessories-care", "箱包清洁护理"),
            ("bag-accessories-repair", "箱包维修配件"),
        ),
    ),
    root(
        "美妆个护",
        group(
            "沐浴与身体护理",
            "fmcg-beauty-and-personal-care-bath-and-body-care",
            ("beauty-bath-body-wash", "沐浴露"),
            ("beauty-bath-soap", "香皂与沐浴皂"),
            ("beauty-bath-salts", "浴盐与泡澡产品"),
            ("beauty-bath-scrub", "身体磨砂"),
            ("beauty-bath-lotion", "身体乳"),
            ("beauty-bath-oil", "身体油"),
            ("beauty-bath-deodorant", "止汗香体"),
            ("beauty-bath-powder", "身体爽身粉"),
            ("beauty-bath-hand-wash", "洗手液"),
            ("beauty-bath-sets", "沐浴身体护理套装"),
        ),
        group(
            "美容与肌肤护理",
            "fmcg-beauty-and-personal-care-beauty-and-skin-care",
            ("beauty-skin-beauty-sets", "美容护理套装"),
            ("beauty-skin-neck-care", "颈部与胸部护理"),
            ("beauty-skin-eye-patches", "眼膜与眼贴"),
            ("beauty-skin-lip-masks", "唇膜"),
            ("beauty-skin-facial-mist", "面部喷雾"),
            ("beauty-skin-massage-cream", "按摩霜"),
            ("beauty-skin-facial-oil", "面部护理油"),
            ("beauty-skin-specialty-care", "局部肌肤护理"),
        ),
        group(
            "美容个护设备",
            "fmcg-beauty-and-personal-care-beauty-personal-care-device",
            ("beauty-device-cleansing", "洁面仪"),
            ("beauty-device-facial", "面部美容仪"),
            ("beauty-device-steamer", "蒸脸器"),
            ("beauty-device-led-mask", "光疗美容面罩"),
            ("beauty-device-massager", "面部按摩仪"),
            ("beauty-device-blackhead", "黑头清洁仪"),
            ("beauty-device-microcurrent", "微电流美容仪"),
            ("beauty-device-skin-analyzer", "皮肤检测仪"),
        ),
        group(
            "眼耳护理",
            "fmcg-beauty-and-personal-care-eye-and-ear-care",
            ("beauty-eye-ear-drops", "眼部护理液"),
            ("beauty-eye-ear-contact-care", "隐形眼镜护理"),
            ("beauty-eye-ear-masks", "眼罩"),
            ("beauty-eye-ear-wipes", "眼部清洁湿巾"),
            ("beauty-eye-ear-cleaning", "耳部清洁"),
            ("beauty-eye-ear-plugs", "耳塞与护耳用品"),
        ),
        group(
            "女性护理",
            "fmcg-beauty-and-personal-care-feminine-care",
            ("beauty-feminine-pads", "卫生巾"),
            ("beauty-feminine-liners", "护垫"),
            ("beauty-feminine-tampons", "卫生棉条"),
            ("beauty-feminine-cups", "月经杯与月经碟"),
            ("beauty-feminine-period-underwear", "经期内裤"),
            ("beauty-feminine-intimate-wash", "私密清洁"),
            ("beauty-feminine-wipes", "女性护理湿巾"),
            ("beauty-feminine-sets", "女性护理套装"),
        ),
        group(
            "头发护理",
            "fmcg-beauty-and-personal-care-hair-care",
            ("beauty-hair-shampoo", "洗发水"),
            ("beauty-hair-conditioner", "护发素"),
            ("beauty-hair-mask", "发膜"),
            ("beauty-hair-oil", "护发精油"),
            ("beauty-hair-scalp", "头皮护理"),
            ("beauty-hair-anti-loss", "防脱护理"),
            ("beauty-hair-growth", "育发护理"),
            ("beauty-hair-dry-shampoo", "免洗与干洗喷雾"),
            ("beauty-hair-sets", "洗护套装"),
        ),
        group(
            "美发造型",
            "fmcg-beauty-and-personal-care-hair-care-and-styling",
            ("beauty-styling-hair-dye", "染发剂"),
            ("beauty-styling-perm", "烫发产品"),
            ("beauty-styling-spray", "定型喷雾"),
            ("beauty-styling-wax", "发蜡与发泥"),
            ("beauty-styling-gel", "发胶与啫喱"),
            ("beauty-styling-curl", "卷发造型产品"),
            ("beauty-styling-straighten", "直发造型产品"),
            ("beauty-styling-volume", "蓬松与丰盈产品"),
        ),
        group(
            "手足与美甲护理",
            "fmcg-beauty-and-personal-care-hand-foot-and-nail-care",
            ("beauty-nail-hand-cream", "护手霜"),
            ("beauty-nail-foot-cream", "足部护理霜"),
            ("beauty-nail-foot-mask", "足膜与去角质"),
            ("beauty-nail-polish", "指甲油"),
            ("beauty-nail-gel", "甲油胶与光疗胶"),
            ("beauty-nail-press-on", "假指甲与穿戴甲"),
            ("beauty-nail-stickers", "美甲贴"),
            ("beauty-nail-tools", "美甲工具"),
            ("beauty-nail-remover", "卸甲产品"),
            ("beauty-nail-care", "指甲护理"),
            ("beauty-nail-decoration", "美甲装饰"),
        ),
        group(
            "彩妆",
            "fmcg-beauty-and-personal-care-makeup-and-perfume",
            ("beauty-makeup-primer", "隔离与妆前"),
            ("beauty-makeup-foundation", "粉底液与粉底霜"),
            ("beauty-makeup-cushion", "气垫"),
            ("beauty-makeup-concealer", "遮瑕"),
            ("beauty-makeup-powder", "粉饼与散粉"),
            ("beauty-makeup-blush", "腮红"),
            ("beauty-makeup-contour", "高光与修容"),
            ("beauty-makeup-eyeshadow", "眼影"),
            ("beauty-makeup-eyeliner", "眼线"),
            ("beauty-makeup-mascara", "睫毛膏"),
            ("beauty-makeup-eyebrow", "眉部彩妆"),
            ("beauty-makeup-lipstick", "唇膏与口红"),
            ("beauty-makeup-lipgloss", "唇釉与唇彩"),
            ("beauty-makeup-palette", "彩妆盘"),
            ("beauty-makeup-setting-spray", "定妆喷雾"),
            ("beauty-makeup-sets", "彩妆套装"),
            ("beauty-makeup-special-effects", "舞台与特效彩妆"),
        ),
        group(
            "男士护理",
            "fmcg-beauty-and-personal-care-men-s-care",
            ("beauty-mens-skincare", "男士面部护理"),
            ("beauty-mens-beard", "胡须护理"),
            ("beauty-mens-shaving-foam", "剃须膏与泡沫"),
            ("beauty-mens-manual-razor", "手动剃须刀"),
            ("beauty-mens-aftershave", "须后护理"),
            ("beauty-mens-body-care", "男士身体护理"),
            ("beauty-mens-hair-styling", "男士发型护理"),
            ("beauty-mens-sets", "男士护理套装"),
        ),
        group(
            "鼻腔与口腔护理",
            "fmcg-beauty-and-personal-care-nasal-and-oral-care",
            ("beauty-oral-toothpaste", "牙膏"),
            ("beauty-oral-toothbrush", "手动牙刷"),
            ("beauty-oral-mouthwash", "漱口水"),
            ("beauty-oral-floss", "牙线与牙间刷"),
            ("beauty-oral-whitening", "牙齿美白"),
            ("beauty-oral-denture", "假牙护理"),
            ("beauty-oral-breath-spray", "口气清新喷雾"),
            ("beauty-nasal-rinse", "鼻腔清洗"),
            ("beauty-nasal-care", "鼻腔护理用品"),
        ),
        group(
            "香水香氛",
            "fmcg-beauty-and-personal-care-perfumes-and-fragrances",
            ("beauty-fragrance-womens", "女士香水"),
            ("beauty-fragrance-mens", "男士香水"),
            ("beauty-fragrance-unisex", "中性香水"),
            ("beauty-fragrance-samples", "香水小样与分装"),
            ("beauty-fragrance-sets", "香水套装"),
            ("beauty-fragrance-body-mist", "身体喷雾"),
            ("beauty-fragrance-solid", "固体香膏"),
            ("beauty-fragrance-hair-mist", "头发香氛"),
        ),
        group(
            "日常个人护理",
            "fmcg-beauty-and-personal-care-personal-care",
            ("beauty-personal-wipes", "个人护理湿巾"),
            ("beauty-personal-cotton-swabs", "棉签"),
            ("beauty-personal-cotton-pads", "化妆棉"),
            ("beauty-personal-tissues", "个人清洁纸品"),
            ("beauty-personal-adult-diapers", "成人纸尿裤"),
            ("beauty-personal-incontinence", "失禁护理用品"),
            ("beauty-personal-hand-sanitizer", "手部清洁消毒"),
            ("beauty-personal-care-sets", "日常个护套装"),
        ),
        group(
            "个护电器",
            "fmcg-beauty-and-personal-care-personal-care-appliances",
            ("beauty-appliance-electric-shaver", "电动剃须刀"),
            ("beauty-appliance-hair-clipper", "理发器"),
            ("beauty-appliance-nose-trimmer", "鼻毛修剪器"),
            ("beauty-appliance-hair-dryer", "吹风机"),
            ("beauty-appliance-curl-straight", "卷发棒与直发器"),
            ("beauty-appliance-electric-toothbrush", "电动牙刷"),
            ("beauty-appliance-oral-irrigator", "冲牙器"),
            ("beauty-appliance-eyebrow-shaper", "电动修眉器"),
            ("beauty-appliance-massage", "个护按摩器"),
            ("beauty-appliance-hair-removal", "脱毛仪"),
        ),
        group(
            "护肤",
            "fmcg-beauty-and-personal-care-skincare",
            ("beauty-skincare-cleanser", "洁面"),
            ("beauty-skincare-makeup-remover", "卸妆"),
            ("beauty-skincare-toner", "化妆水与爽肤水"),
            ("beauty-skincare-serum", "面部精华"),
            ("beauty-skincare-moisturizer", "乳液与面霜"),
            ("beauty-skincare-eye", "眼部护理"),
            ("beauty-skincare-lip", "唇部护理"),
            ("beauty-skincare-mask", "面膜"),
            ("beauty-skincare-sunscreen", "防晒"),
            ("beauty-skincare-exfoliator", "去角质"),
            ("beauty-skincare-acne", "祛痘护理"),
            ("beauty-skincare-brightening", "美白淡斑"),
            ("beauty-skincare-sets", "护肤套装"),
        ),
        group(
            "特殊个人护理",
            "fmcg-beauty-and-personal-care-special-personal-care",
            ("beauty-special-hair-removal-cream", "脱毛膏"),
            ("beauty-special-hair-removal-wax", "脱毛蜡与脱毛贴"),
            ("beauty-special-intimate-care", "特殊私密护理"),
            ("beauty-special-postpartum", "产后个人护理"),
            ("beauty-special-scar-care", "疤痕护理"),
            ("beauty-special-tattoo-care", "纹身护理"),
            ("beauty-special-sensitive-skin", "特殊敏感肌护理"),
        ),
    ),
)


def iter_taxonomy_leaves():
    for category_root in CATEGORY_TAXONOMY:
        for category_group in category_root["children"]:
            for code, label in category_group["children"]:
                yield category_root["label"], category_group["label"], code, label, category_group["rule_code"]
