# Generated by Django 5.2.16 on 2026-07-14 17:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(default='other', max_length=40)),
                ('url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('seller', models.CharField(blank=True, max_length=160)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('inactive', '停用')], default='draft', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已下单'), ('partial', '部分收货'), ('received', '已收货'), ('cancelled', '已取消')], default='draft', max_length=16)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('draft', '待收货'), ('completed', '已收货')], default='draft', max_length=16)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='erp.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '待锁库'), ('allocated', '已锁库'), ('shipped', '已出库'), ('cancelled', '已取消')], default='draft', max_length=16)),
                ('external_ref', models.CharField(blank=True, max_length=100)),
                ('customer', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('requested', '待收货'), ('received', '已收货'), ('rejected', '已拒绝')], default='requested', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('original_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='erp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('quantity_shipped', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('completed', '已出库')], default='completed', max_length=16)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('shipped_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='erp.salesorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('safety_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='erp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.salesorderline')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.shipment')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.sku')),
            ],
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='erp.sku'),
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_expected', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('condition', models.CharField(choices=[('restock', '可重新入库'), ('damaged', '残损')], default='restock', max_length=16)),
                ('unit_refund', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.returnorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.sku')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.receipt')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='erp.sku')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='erp.sku'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='erp.supplier'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(default='CN', max_length=2)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('active', '有效'), ('released', '已释放'), ('consumed', '已出库')], default='active', max_length=16)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.salesorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('receipt', '采购收货'), ('adjustment', '库存调整'), ('reserve', '锁定'), ('release', '释放'), ('shipment', '出库'), ('return', '退货入库')], max_length=20)),
                ('on_hand_delta', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('reserved_delta', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('on_hand_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reserved_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reference_type', models.CharField(max_length=40)),
                ('reference_id', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='erp.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='erp.warehouse')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='erp.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='erp.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='erp.warehouse'),
        ),
        migrations.CreateModel(
            name='CompetitorSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('sold_count', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('review_count', models.BigIntegerField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=40)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='erp.competitorproduct')),
            ],
            options={
                'ordering': ['-captured_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'captured_at'), name='uniq_competitor_capture')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', '管理员'), ('manager', '经理'), ('buyer', '采购'), ('warehouse', '仓库'), ('viewer', '只读')], default='viewer', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='erp.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uniq_org_user')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='erp.product')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'position'), name='uniq_product_image_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_org_sku_code'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('organization', 'barcode'), name='uniq_org_sku_barcode'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='sku_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.CheckConstraint(condition=models.Q(('safety_stock__gte', 0)), name='sku_safety_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shipmentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shipment_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'sku'), name='uniq_order_sku'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='order_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_shipped__gte', 0)), name='order_shipped_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='receipt_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='receipt_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'sku'), name='uniq_po_sku'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='po_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='po_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='po_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_org_supplier_code'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_org_warehouse_code'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_reservation_idem'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_ledger_idem'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('organization', 'warehouse', 'sku'), name='uniq_stock_balance'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='stock_on_hand_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='stock_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='stock_reserved_lte_on_hand'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_org_shipment_number'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_shipment_idem'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_org_order_number'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('organization', 'external_ref'), name='uniq_org_order_ext'),
        ),
        migrations.AddConstraint(
            model_name='returnorder',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_org_return_number'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_org_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_receipt_idem'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_org_po_number'),
        ),
    ]
