# Generated by Django 5.2.16 on 2026-07-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_expected__gt', 0)), name='return_expected_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='return_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__lte', models.F('quantity_expected'))), name='return_received_lte_expected'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_refund__gte', 0)), name='return_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_qty_positive'),
        ),
    ]
