# Generated by Django 5.2.16 on 2026-07-14 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_returnline_return_expected_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('requested', '待收货'), ('partial', '部分收货'), ('received', '已收货'), ('rejected', '已拒绝')], default='requested', max_length=16),
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('received_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='erp.returnorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_receipts', to='erp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('condition', models.CharField(choices=[('restock', '可重新入库'), ('damaged', '残损')], max_length=16)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.returnreceipt')),
                ('return_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='erp.returnline')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.sku')),
            ],
        ),
        migrations.AddConstraint(
            model_name='returnreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_return_receipt_idem'),
        ),
        migrations.AddConstraint(
            model_name='returnreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'return_line'), name='uniq_return_receipt_line'),
        ),
        migrations.AddConstraint(
            model_name='returnreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='return_receipt_qty_positive'),
        ),
    ]
