# Generated by Django 5.2.16 on 2026-07-14 18:11

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_returnorder_status_returnreceipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__lte', models.F('quantity_ordered'))), name='po_received_lte_ordered'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '-', models.F('quantity_shipped')))), name='order_reserved_plus_shipped_lte_qty'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_after__gte', 0)), name='ledger_on_hand_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_after__gte', 0)), name='ledger_reserved_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_after__lte', models.F('on_hand_after'))), name='ledger_reserved_after_lte_on_hand'),
        ),
    ]
