# Generated by Django 5.2.16 on 2026-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_purchaseorderline_po_received_lte_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
