# Generated by Django 5.2.16 on 2026-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_shipment_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_url',
            field=models.URLField(blank=True),
        ),
    ]
