# Generated by Django 5.2.16 on 2026-07-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_product_purchase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='erp.supplier'),
        ),
    ]
