# Generated by Django 5.2.16 on 2026-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_product_default_supplier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitorsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='competitor_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='competitorsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('sold_count__isnull', True), ('sold_count__gte', 0), _connector='OR'), name='competitor_sold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='competitorsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 0), ('rating__lte', 5)), _connector='OR'), name='competitor_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='competitorsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('review_count__isnull', True), ('review_count__gte', 0), _connector='OR'), name='competitor_reviews_nonnegative'),
        ),
    ]
