# Generated by Django 5.2.16 on 2026-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_competitorsnapshot_competitor_price_nonnegative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('ready', '待锁库'), ('allocated', '已锁库'), ('picking', '拣货中'), ('verified', '已复核'), ('shipped', '已出库'), ('cancelled', '已取消')], default='draft', max_length=16),
        ),
    ]
