# Generated by Django 5.2 on 2026-07-15

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_alter_salesorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="market",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_currency",
            field=models.CharField(default="CNY", max_length=3),
        ),
        migrations.AddField(
            model_name="product",
            name="monitoring_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="extra_cost",
            field=models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=14),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="platform",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="store",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="ordered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competitorproduct",
            name="kind",
            field=models.CharField(
                choices=[("direct", "直接竞品"), ("indirect", "间接竞品")],
                default="direct",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="competitorproduct",
            name="market",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="competitorproduct",
            name="linked_product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitoring_profile",
                to="erp.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("extra_cost__gte", 0)),
                name="po_extra_cost_nonnegative",
            ),
        ),
    ]
