# Generated by Django 5.2 on 2026-07-15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_team_frontend_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalImport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("source_version", models.PositiveIntegerField(default=0)),
                ("source_hash", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("completed", "已完成")], default="completed", max_length=16)),
                ("summary", models.JSONField(default=dict)),
                ("mapping", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="erp.organization")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="local_imports", to="erp.warehouse")),
                ("imported_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="erp_local_imports", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-imported_at", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="localimport",
            constraint=models.UniqueConstraint(fields=("organization",), name="uniq_org_local_import"),
        ),
        migrations.AddConstraint(
            model_name="localimport",
            constraint=models.UniqueConstraint(fields=("organization", "idempotency_key"), name="uniq_org_local_import_idem"),
        ),
        migrations.AddConstraint(
            model_name="localimport",
            constraint=models.UniqueConstraint(fields=("organization", "source_hash"), name="uniq_org_local_import_hash"),
        ),
    ]
