# Generated by Django 5.2.16 on 2026-07-15 03:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_localimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='can_receive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='can_ship',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('overseas', '海外仓'), ('forwarder', '货代仓'), ('school', '学校仓'), ('domestic', '国内仓'), ('other', '其他')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='event_type',
            field=models.CharField(choices=[('receipt', '采购收货'), ('adjustment', '库存调整'), ('reserve', '锁定'), ('release', '释放'), ('shipment', '出库'), ('return', '退货入库'), ('transfer_out', '调拨发出'), ('transfer_in', '调拨收货'), ('transfer_cancel', '调拨撤回')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_transit', '调拨在途'), ('received', '已收货'), ('cancelled', '已取消')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('dispatch_idempotency_key', models.CharField(blank=True, max_length=120)),
                ('receive_idempotency_key', models.CharField(blank=True, max_length=120)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='erp.warehouse')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='erp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='erp.sku')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='ReplenishmentPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_time_override', models.PositiveIntegerField(blank=True, null=True)),
                ('review_cycle_days', models.PositiveIntegerField(default=7)),
                ('target_days', models.PositiveIntegerField(default=30)),
                ('min_order_qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14)),
                ('pack_size', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14)),
                ('safety_stock_override', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_policies', to='erp.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_policies', to='erp.warehouse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'warehouse', 'sku'), name='uniq_replenishment_policy'), models.CheckConstraint(condition=models.Q(('review_cycle_days__gt', 0)), name='replenishment_review_positive'), models.CheckConstraint(condition=models.Q(('target_days__gt', 0)), name='replenishment_target_positive'), models.CheckConstraint(condition=models.Q(('min_order_qty__gt', 0)), name='replenishment_moq_positive'), models.CheckConstraint(condition=models.Q(('pack_size__gt', 0)), name='replenishment_pack_positive'), models.CheckConstraint(condition=models.Q(('safety_stock_override__isnull', True), ('safety_stock_override__gte', 0), _connector='OR'), name='replenishment_safety_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_org_transfer_number'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('dispatch_idempotency_key', ''), _negated=True), fields=('organization', 'dispatch_idempotency_key'), name='uniq_org_transfer_dispatch_idem'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('receive_idempotency_key', ''), _negated=True), fields=('organization', 'receive_idempotency_key'), name='uniq_org_transfer_receive_idem'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_warehouse', models.F('destination_warehouse')), _negated=True), name='transfer_warehouses_differ'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'sku'), name='uniq_transfer_sku'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_qty_positive'),
        ),
    ]
