# Generated by Django 5.2.16 on 2026-07-15 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_warehouse_can_receive_warehouse_can_ship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localimport',
            options={'ordering': ['-imported_at', '-created_at'], 'verbose_name': '本地导入记录', 'verbose_name_plural': '本地导入记录'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': '成员关系', 'verbose_name_plural': '成员关系'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='replenishmentpolicy',
            options={'verbose_name': '补货策略', 'verbose_name_plural': '补货策略'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name': '库存单位（SKU）', 'verbose_name_plural': '库存单位（SKU）'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'verbose_name': '库存调拨单', 'verbose_name_plural': '库存调拨'},
        ),
        migrations.AlterModelOptions(
            name='stocktransferline',
            options={'verbose_name': '调拨明细', 'verbose_name_plural': '调拨明细'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': '仓库', 'verbose_name_plural': '仓库'},
        ),
        migrations.AlterField(
            model_name='localimport',
            name='idempotency_key',
            field=models.CharField(max_length=160, verbose_name='幂等键'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='导入时间'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_local_imports', to=settings.AUTH_USER_MODEL, verbose_name='导入人'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='mapping',
            field=models.JSONField(default=dict, verbose_name='字段映射'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='source_hash',
            field=models.CharField(max_length=64, verbose_name='来源校验值'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='source_version',
            field=models.PositiveIntegerField(default=0, verbose_name='来源版本'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='status',
            field=models.CharField(choices=[('completed', '已完成')], default='completed', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='summary',
            field=models.JSONField(default=dict, verbose_name='导入摘要'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_imports', to='erp.warehouse', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='localimport',
            name='warnings',
            field=models.JSONField(default=list, verbose_name='警告信息'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='erp.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('manager', '经理'), ('buyer', '采购'), ('warehouse', '仓库'), ('viewer', '只读')], default='viewer', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=120, verbose_name='组织名称'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='组织标识'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='erp.supplier', verbose_name='默认供应商'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.CharField(blank=True, max_length=8, verbose_name='销售市场'),
        ),
        migrations.AlterField(
            model_name='product',
            name='monitoring_enabled',
            field=models.BooleanField(default=False, verbose_name='启用监控'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_url',
            field=models.URLField(blank=True, verbose_name='采购链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_currency',
            field=models.CharField(default='CNY', max_length=3, verbose_name='销售币种'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(blank=True, max_length=160, verbose_name='店铺/卖家'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='来源链接'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('inactive', '停用')], default='draft', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='lead_time_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='补货提前期（天）'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='min_order_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, verbose_name='最小订购量'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='pack_size',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14, verbose_name='整箱数量'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='review_cycle_days',
            field=models.PositiveIntegerField(default=7, verbose_name='复核周期（天）'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='safety_stock_override',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='安全库存覆盖值'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_policies', to='erp.sku', verbose_name='库存单位（SKU）'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='target_days',
            field=models.PositiveIntegerField(default=30, verbose_name='目标覆盖天数'),
        ),
        migrations.AlterField(
            model_name='replenishmentpolicy',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_policies', to='erp.warehouse', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='规格属性'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='barcode',
            field=models.CharField(blank=True, max_length=80, verbose_name='条形码'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(max_length=80, verbose_name='库存单位编码（SKU）'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='成本'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='currency',
            field=models.CharField(default='CNY', max_length=3, verbose_name='成本币种'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='erp.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='safety_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='安全库存'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='erp.warehouse', verbose_name='调入仓库'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='dispatch_idempotency_key',
            field=models.CharField(blank=True, max_length=120, verbose_name='发出幂等键'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发出时间'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='发出人'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='number',
            field=models.CharField(max_length=60, verbose_name='调拨单号'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='receive_idempotency_key',
            field=models.CharField(blank=True, max_length=120, verbose_name='收货幂等键'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收货时间'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='erp.warehouse', verbose_name='调出仓库'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('in_transit', '调拨在途'), ('received', '已收货'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='erp.sku', verbose_name='库存单位（SKU）'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.stocktransfer', verbose_name='调拨单'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=40, verbose_name='供应商编码'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.JSONField(blank=True, default=dict, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=160, verbose_name='供应商名称'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.JSONField(blank=True, default=dict, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='can_receive',
            field=models.BooleanField(default=True, verbose_name='允许收货'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='can_ship',
            field=models.BooleanField(default=True, verbose_name='允许发货'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=40, verbose_name='仓库编码'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='contact',
            field=models.JSONField(blank=True, default=dict, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='CN', max_length=2, verbose_name='国家/地区代码'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=120, verbose_name='仓库名称'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('overseas', '海外仓'), ('forwarder', '货代仓'), ('school', '学校仓'), ('domestic', '国内仓'), ('other', '其他')], default='other', max_length=20, verbose_name='仓库类型'),
        ),
    ]
