# Generated by Django 5.2.16 on 2026-08-03 19:24

import django.db.models.deletion
import hashlib
import uuid
from django.db import migrations, models


def group_existing_competitors(apps, schema_editor):
    Product = apps.get_model("erp", "CompetitorProduct")
    Group = apps.get_model("erp", "CompetitorSellerGroup")
    for product in Product.objects.exclude(seller="").iterator():
        normalized = " ".join(product.seller.strip().casefold().split())
        group, _ = Group.objects.get_or_create(
            organization_id=product.organization_id,
            normalized_name=normalized,
            defaults={"display_name": product.seller.strip()},
        )
        product.seller_group_id = group.pk
        product.save(update_fields=["seller_group"])


def hash_existing_competitor_snapshots(apps, schema_editor):
    Snapshot = apps.get_model("erp", "CompetitorSnapshot")
    fields = ("price", "sold_count", "rating", "review_count", "availability", "shipping_type")
    for snapshot in Snapshot.objects.iterator():
        signature = "|".join(
            "" if getattr(snapshot, field) is None else str(getattr(snapshot, field))
            for field in fields
        )
        snapshot.value_hash = hashlib.sha256(signature.encode()).hexdigest()
        snapshot.save(update_fields=["value_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_stocktransfer_partial_receipts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sku',
            name='uniq_org_sku_code',
        ),
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(max_length=80, unique=True, verbose_name='库存单位编码（SKU）'),
        ),
        migrations.AddField(
            model_name='competitorproduct',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitorproduct',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('local', '本土发货'), ('cross_border', '跨境发货')], max_length=20),
        ),
        migrations.AddField(
            model_name='competitorsnapshot',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='competitorsnapshot',
            name='value_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(hash_existing_competitor_snapshots, migrations.RunPython.noop),
        migrations.AddField(
            model_name='sku',
            name='category_code',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='default_creator_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='image_url',
            field=models.URLField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='sku',
            name='packed_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='purchase_cost_cny',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='CompetitorSellerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_name', models.CharField(max_length=160)),
                ('display_name', models.CharField(max_length=160)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_star', models.BooleanField(default=False)),
                ('seller_type', models.CharField(choices=[('brand', '品牌卖家'), ('normal', '普通卖家')], default='normal', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
        ),
        migrations.AddField(
            model_name='competitorproduct',
            name='seller_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='erp.competitorsellergroup'),
        ),
        migrations.RunPython(group_existing_competitors, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CompetitorSellerSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_star', models.BooleanField(default=False)),
                ('seller_type', models.CharField(max_length=20)),
                ('value_hash', models.CharField(max_length=64)),
                ('seller_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='erp.competitorsellergroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField()),
                ('fetched_at', models.DateTimeField()),
                ('myr_cny', models.DecimalField(decimal_places=6, max_digits=14)),
                ('myr_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(max_length=80)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('used_history_fallback', models.BooleanField(default=False)),
                ('validation_status', models.CharField(default='valid', max_length=32)),
                ('response_summary', models.CharField(blank=True, max_length=500)),
                ('is_current', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['-fetched_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('platform', models.CharField(default='TikTok Shop', max_length=80)),
                ('market', models.CharField(default='马来西亚', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_price_myr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product_url', models.URLField(blank=True, max_length=2000)),
                ('commission_override_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('include_in_list_calculation', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_products', to='erp.sku')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_products', to='erp.ownstore')),
            ],
        ),
        migrations.AddConstraint(
            model_name='competitorsellergroup',
            constraint=models.UniqueConstraint(fields=('organization', 'normalized_name'), name='uniq_org_competitor_seller_name'),
        ),
        migrations.AddConstraint(
            model_name='competitorsellersnapshot',
            constraint=models.UniqueConstraint(fields=('seller_group', 'value_hash'), name='uniq_competitor_seller_snapshot_hash'),
        ),
        migrations.AddConstraint(
            model_name='exchangeratesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('organization',), name='uniq_org_current_exchange_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='exchangeratesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('myr_cny__gt', 0), ('myr_usd__gt', 0)), name='exchange_rates_positive'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='uniq_store_sku_product'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price_myr__gte', 0)), name='store_product_price_nonnegative'),
        ),
    ]
