# Generated by Django 5.2.16 on 2026-08-10 18:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


def migrate_replenishment_history(apps, schema_editor):
    Warehouse = apps.get_model('erp', 'Warehouse')
    ReplenishmentSettings = apps.get_model('erp', 'ReplenishmentSettings')
    ReplenishmentPolicy = apps.get_model('erp', 'ReplenishmentPolicy')
    PurchaseShipment = apps.get_model('erp', 'PurchaseShipment')
    PurchaseShipmentLine = apps.get_model('erp', 'PurchaseShipmentLine')
    StockTransfer = apps.get_model('erp', 'StockTransfer')
    StockTransferPackage = apps.get_model('erp', 'StockTransferPackage')
    StockTransferPackageLine = apps.get_model('erp', 'StockTransferPackageLine')
    StockBalance = apps.get_model('erp', 'StockBalance')

    for settings in ReplenishmentSettings.objects.all().iterator():
        Warehouse.objects.filter(organization_id=settings.organization_id).update(
            default_lead_time_days=models.Case(
                models.When(default_lead_time_days__isnull=True, then=settings.default_lead_time_days),
                default=models.F('default_lead_time_days'),
                output_field=models.IntegerField(),
            ),
            default_coverage_days=models.Case(
                models.When(default_coverage_days__isnull=True, then=settings.target_days),
                default=models.F('default_coverage_days'),
                output_field=models.IntegerField(),
            ),
        )
    ReplenishmentPolicy.objects.filter(coverage_days__isnull=True).update(
        coverage_days=models.F('review_cycle_days'), replenishment_enabled=True,
    )

    # Existing shipment records represent historically confirmed logistics.
    PurchaseShipment.objects.filter(confirmed_at__isnull=True, lines__isnull=False).update(
        confirmed_at=models.F('created_at'),
    )

    # Preserve legacy in-transit transfer quantities in the new balance field
    # and create a single compatibility package for the old dispatch record.
    for transfer in StockTransfer.objects.filter(status__in=['IN_TRANSIT', 'PARTIALLY_RECEIVED']).prefetch_related('lines').iterator(chunk_size=100):
        package, _ = StockTransferPackage.objects.get_or_create(
            transfer_id=transfer.pk,
            defaults={'organization_id': transfer.organization_id, 'tracking_number': '', 'confirmed_at': transfer.dispatched_at},
        )
        for line in transfer.lines.all():
            remaining = Decimal(line.quantity) - Decimal(line.received_quantity or 0)
            if remaining <= 0:
                continue
            StockTransferPackageLine.objects.get_or_create(package_id=package.pk, sku_id=line.sku_id, defaults={'quantity': line.quantity})
            balance, _ = StockBalance.objects.get_or_create(organization_id=transfer.organization_id, warehouse_id=transfer.destination_warehouse_id, sku_id=line.sku_id, defaults={'on_hand': 0, 'reserved': 0, 'purchased_pending_shipment': 0, 'in_transit': 0})
            balance.in_transit = Decimal(balance.in_transit or 0) + remaining
            balance.save(update_fields=['in_transit', 'updated_at'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_profitcalculationstrategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseShipmentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseShipmentPackageLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='ReplenishmentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_at', models.DateTimeField()),
                ('calculation_version', models.CharField(default='v1', max_length=40)),
                ('system_suggested_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('user_confirmed_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('converted_purchase_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('suggested', '系统建议'), ('confirmed', '已确认'), ('partially_converted', '部分转采购'), ('converted', '已转采购'), ('closed', '已关闭')], default='suggested', max_length=24)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('conversion_idempotency_key', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferPackageLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
        ),
        migrations.AddField(
            model_name='ownstore',
            name='custom_platform_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ownstore',
            name='platform_code',
            field=models.CharField(default='tiktok_shop', max_length=40),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='closed_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_purchase_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replenishmentpolicy',
            name='coverage_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replenishmentpolicy',
            name='replenishment_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='in_transit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='purchased_pending_shipment',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='exception_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='external_listing_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='external_sku_code',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='tiktokshopconnection',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiktok_connections', to='erp.ownstore'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='default_coverage_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='default_lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownstore',
            name='market',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='ownstore',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='purchaseshipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='erp.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('in_transit', '调拨在途'), ('partially_received', '部分收货'), ('received', '已收货'), ('cancelled', '已取消'), ('completed_with_exception', '已完成（有异常）')], default='draft', max_length=32, verbose_name='状态'),
        ),
        migrations.AddConstraint(
            model_name='ownstore',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_org_own_store_name'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('external_sku_code', ''), _negated=True), fields=('store', 'external_sku_code'), name='uniq_store_external_sku'),
        ),
        migrations.AddField(
            model_name='purchaseshipmentpackage',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='erp.purchaseshipment'),
        ),
        migrations.AddField(
            model_name='purchaseshipmentpackageline',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.purchaseshipmentpackage'),
        ),
        migrations.AddField(
            model_name='purchaseshipmentpackageline',
            name='purchase_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_lines', to='erp.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='replenishmentrecommendation',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_replenishment_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replenishmentrecommendation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='replenishmentrecommendation',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_recommendations', to='erp.sku'),
        ),
        migrations.AddField(
            model_name='replenishmentrecommendation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_recommendations', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferpackage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stocktransferpackage',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='erp.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferpackageline',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.stocktransferpackage'),
        ),
        migrations.AddField(
            model_name='stocktransferpackageline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.sku'),
        ),
        migrations.AddConstraint(
            model_name='purchaseshipmentpackageline',
            constraint=models.UniqueConstraint(fields=('package', 'purchase_line'), name='uniq_purchase_package_line'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('system_suggested_quantity__gte', 0)), name='recommendation_system_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('converted_purchase_quantity__gte', 0)), name='recommendation_converted_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('conversion_idempotency_key', ''), _negated=True), fields=('organization', 'conversion_idempotency_key'), name='uniq_recommendation_conversion_idem'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferpackageline',
            constraint=models.UniqueConstraint(fields=('package', 'sku'), name='uniq_transfer_package_sku'),
        ),
        migrations.RunPython(migrate_replenishment_history, noop),
    ]
