# Generated by Django 5.2.16 on 2026-08-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_replenishment_intransit_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='external_listing_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='external_sku_code',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='erp.sku'),
        ),
    ]
