# Generated by Codex for ERP-REPLENISHMENT-INTRANSIT-STORE-20260811 remediation.

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0029_sales_order_external_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="quantity_unshipped_closed",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=14),
        ),
        migrations.AddField(
            model_name="purchaseshipmentline",
            name="quantity_exception_closed",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=14),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="event_type",
            field=models.CharField(choices=[
                ("receipt", "采购收货"), ("adjustment", "库存调整"), ("reserve", "锁定"),
                ("release", "释放"), ("shipment", "出库"), ("return", "退货入库"),
                ("transfer_out", "调拨发出"), ("transfer_in", "调拨收货"),
                ("purchase_pending", "采购待发货"), ("purchase_transit", "采购在途"),
                ("transfer_transit", "调拨在途"), ("transfer_cancel", "调拨撤回"),
                ("manual_inbound", "手动入库"), ("manual_outbound", "手动出库"), ("reversal", "库存流水撤回"),
            ], max_length=20),
        ),
        migrations.CreateModel(
            name="ReplenishmentConversionEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="erp.organization")),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="replenishment_conversion_events", to="erp.purchaseorder")),
                ("recommendation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="conversion_events", to="erp.replenishmentrecommendation")),
            ],
        ),
        migrations.AddConstraint(
            model_name="replenishmentconversionevent",
            constraint=models.UniqueConstraint(fields=("organization", "idempotency_key"), name="uniq_replenishment_conversion_event_idem"),
        ),
        migrations.AddConstraint(
            model_name="replenishmentconversionevent",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="replenishment_conversion_event_positive"),
        ),
    ]
