# Generated by Django 5.2.16 on 2026-08-20 16:34

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def verify_transfer_line_quantities(apps, schema_editor):
    """Fail safely before adding production integrity constraints.

    This migration deliberately never "repairs" inventory history.  Operators must
    audit and correct any inconsistent legacy transfer before applying the schema
    constraints, with a database backup available for rollback.
    """
    StockTransferLine = apps.get_model("erp", "StockTransferLine")
    invalid = StockTransferLine.objects.filter(
        models.Q(received_quantity__lt=0)
        | models.Q(exception_closed_quantity__lt=0)
        | models.Q(received_quantity__gt=models.F("quantity") - models.F("exception_closed_quantity"))
    )
    samples = list(invalid.values_list("id", flat=True)[:10])
    if samples:
        raise RuntimeError(
            "检测到 %s 条历史调拨数量不一致（示例：%s）。迁移已停止，未修改数据；"
            "请先备份并按库存流水人工核对修复。" % (invalid.count(), ", ".join(map(str, samples)))
        )


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_erp_ui_workflow_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', '手工录入'), ('authorized', '平台正式授权')], max_length=16)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('units', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('gmv', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('attributed_on', models.DateField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorCollaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('pending', '待联系'), ('contacted', '已联系'), ('negotiating', '洽谈中'), ('sampling', '寄样中'), ('publishing', '待发布'), ('published', '已发布'), ('completed', '已完成'), ('paused', '暂停')], default='pending', max_length=24)),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fixed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(blank=True, max_length=40)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreatorFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('next_reminder_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('account_name', models.CharField(blank=True, max_length=160)),
                ('profile_url', models.URLField(blank=True, max_length=2000)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(blank=True, max_length=80)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('follower_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=160)),
                ('cooperation_status', models.CharField(choices=[('pending', '待联系'), ('contacted', '已联系'), ('negotiating', '洽谈中'), ('sampling', '寄样中'), ('publishing', '待发布'), ('published', '已发布'), ('completed', '已完成'), ('paused', '暂停')], default='pending', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['is_archived', 'display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreatorSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=14)),
                ('tracking_number', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', '待寄出'), ('shipped', '已寄出'), ('received', '已签收'), ('exception', '物流异常')], default='pending', max_length=16)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitCalculationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('request_snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', '有效'), ('archived', '已归档')], default='active', max_length=16)),
                ('sku_code_snapshot', models.CharField(max_length=160)),
                ('sku_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('image_url_snapshot', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfitPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('exchange_rate_snapshot', models.JSONField(default=dict)),
                ('rule_version', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferCompletionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=240)),
                ('quantities', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='profitcalculationworkingconfig',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='异常结束时间'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='异常结束人'),
        ),
        migrations.RunPython(verify_transfer_line_quantities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='transfer_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('exception_closed_quantity__gte', 0)), name='transfer_exception_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '-', models.F('exception_closed_quantity')))), name='transfer_received_exception_lte_qty'),
        ),
        migrations.AddField(
            model_name='creatorattribution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='creatorattribution',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_creator_attributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorattribution',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_attributions', to='erp.ownstore'),
        ),
        migrations.AddField(
            model_name='creatorcollaboration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_creator_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorcollaboration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='creatorcollaboration',
            name='responsible_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_creator_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorcollaboration',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_collaborations', to='erp.sku'),
        ),
        migrations.AddField(
            model_name='creatorcollaboration',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_collaborations', to='erp.ownstore'),
        ),
        migrations.AddField(
            model_name='creatorcollaboration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_creator_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorattribution',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='erp.creatorcollaboration'),
        ),
        migrations.AddField(
            model_name='creatorcontent',
            name='collaboration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='erp.creatorcollaboration'),
        ),
        migrations.AddField(
            model_name='creatorcontent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='creatorfollowup',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='erp.creatorcollaboration'),
        ),
        migrations.AddField(
            model_name='creatorfollowup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_creator_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorfollowup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='creatorfollowup',
            name='responsible_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_creator_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_creator_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_creator_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='responsible_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_creator_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_creator_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorfollowup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='erp.creatorprofile'),
        ),
        migrations.AddField(
            model_name='creatorcollaboration',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborations', to='erp.creatorprofile'),
        ),
        migrations.AddField(
            model_name='creatorattribution',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='erp.creatorprofile'),
        ),
        migrations.AddField(
            model_name='creatorsample',
            name='collaboration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='erp.creatorcollaboration'),
        ),
        migrations.AddField(
            model_name='creatorsample',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='creatorsample',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_samples', to='erp.sku'),
        ),
        migrations.AddField(
            model_name='profitcalculationbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_calculation_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitcalculationbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='profitplan',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_profit_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profit_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='profitplan',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profit_plans', to='erp.sku'),
        ),
        migrations.AddField(
            model_name='profitplan',
            name='source_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='erp.profitcalculationbatch'),
        ),
        migrations.AddField(
            model_name='profitplan',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profit_plans', to='erp.ownstore'),
        ),
        migrations.AddField(
            model_name='profitplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profit_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitplanversion',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='erp.profitcalculationbatch'),
        ),
        migrations.AddField(
            model_name='profitplanversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profit_plan_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitplanversion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='profitplanversion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='erp.profitplan'),
        ),
        migrations.AddField(
            model_name='stocktransfercompletionevent',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_completion_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfercompletionevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stocktransfercompletionevent',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_event', to='erp.stocktransfer'),
        ),
        migrations.AddConstraint(
            model_name='creatorcollaboration',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__isnull', True), models.Q(('commission_percent__gte', 0), ('commission_percent__lte', 100)), _connector='OR'), name='creator_collaboration_commission_range'),
        ),
        migrations.AddConstraint(
            model_name='creatorcollaboration',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_fee__isnull', True), ('fixed_fee__gte', 0), _connector='OR'), name='creator_collaboration_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creatorattribution',
            constraint=models.CheckConstraint(condition=models.Q(('units__gte', 0)), name='creator_attribution_units_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creatorattribution',
            constraint=models.CheckConstraint(condition=models.Q(('gmv__isnull', True), ('gmv__gte', 0), _connector='OR'), name='creator_attribution_gmv_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creatorsample',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='creator_sample_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='profitcalculationbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_profit_batch_idem'),
        ),
        migrations.AddIndex(
            model_name='profitplan',
            index=models.Index(fields=['organization', 'sku_code_snapshot', 'status'], name='erp_profitp_organiz_973f2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='profitplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_number'), name='uniq_profit_plan_version_number'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfercompletionevent',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_transfer_completion_idem'),
        ),
    ]
