# Generated by Django 5.2.16 on 2026-09-10 03:05

from django.conf import settings
from django.db import migrations, models


def guard_reverse(apps, schema_editor):
    shipments = apps.get_model('erp', 'PurchaseShipment').objects.using(schema_editor.connection.alias)
    if shipments.exclude(domestic_tracking_number='', international_tracking_number='').exists():
        raise RuntimeError('Cannot reverse 0037: preserve the new logistics data; roll back application code only.')
    if shipments.filter(tracking_number='').values('purchase_order').annotate(n=models.Count('id')).filter(n__gt=1).exists():
        raise RuntimeError('Cannot reverse 0037: multiple unnumbered packages exist; do not delete package history.')


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_stock_transfer_exception_close_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseshipment',
            name='uniq_purchase_tracking_number',
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='domestic_tracking_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=120),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='international_tracking_number',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='purchaseshipment',
            constraint=models.UniqueConstraint(condition=models.Q(('tracking_number', ''), _negated=True), fields=('purchase_order', 'tracking_number'), name='uniq_purchase_tracking_number'),
        ),
        migrations.RunPython(migrations.RunPython.noop, guard_reverse),
    ]
