# Generated by Django 5.2.16 on 2026-09-22 01:15

import apps.erp.scheduling_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_purchase_domestic_international_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('first_monday', models.DateField()),
                ('week_count', models.PositiveSmallIntegerField(default=20)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('periods', models.JSONField(default=apps.erp.scheduling_models.default_periods)),
                ('locked_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('recognition_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.aiproviderconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberWeekPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_index', models.PositiveSmallIntegerField()),
                ('week_start', models.DateField()),
                ('confirmed_grid', models.JSONField(default=list)),
                ('weekend_day', models.CharField(default='sat', max_length=3)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.scheduleterm')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private_file', models.CharField(max_length=250)),
                ('sha256', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=250)),
                ('content_type', models.CharField(max_length=40)),
                ('size', models.PositiveIntegerField()),
                ('pixel_width', models.PositiveIntegerField()),
                ('pixel_height', models.PositiveIntegerField()),
                ('archived_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberWeekPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('grid', models.JSONField()),
                ('weekend_day', models.CharField(max_length=3)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='erp.memberweekplan')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.timetableevidence')),
            ],
        ),
        migrations.AddField(
            model_name='memberweekplan',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.timetableevidence'),
        ),
        migrations.CreateModel(
            name='TimetableImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='draft', max_length=16)),
                ('draft_grid', models.JSONField(default=list)),
                ('selected_weeks', models.JSONField(default=list)),
                ('weekend_day', models.CharField(default='sat', max_length=3)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.timetableevidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.scheduleterm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='memberweekplan',
            name='source_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.timetableimport'),
        ),
        migrations.CreateModel(
            name='TimetableRecognitionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_revision', models.PositiveIntegerField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('attempt_history', models.JSONField(default=list)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('available_at', models.DateTimeField(null=True)),
                ('sanitized_error', models.CharField(blank=True, max_length=500)),
                ('candidate_grid', models.JSONField(default=list)),
                ('recognition_warnings', models.JSONField(default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.aiproviderconfig')),
                ('timetable_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='erp.timetableimport')),
            ],
        ),
        migrations.CreateModel(
            name='WorkScheduleCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('period', models.PositiveSmallIntegerField()),
                ('base_status', models.CharField(max_length=12)),
                ('effective_status', models.CharField(max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('period_start', models.TimeField()),
                ('period_end', models.TimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.memberweekplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'actor', 'idempotency_key'), name='sched_mutation_unique')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('period', models.PositiveSmallIntegerField()),
                ('authority', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=12)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('show_annotation', models.BooleanField(default=True)),
                ('force', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=500)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('organization', 'owner', 'date', 'period', 'authority'), name='sched_active_override_unique')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='sched_participant_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='timetableevidence',
            index=models.Index(fields=['organization', 'owner', 'created_at'], name='sched_evidence_owner'),
        ),
        migrations.AddConstraint(
            model_name='memberweekplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='sched_plan_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='memberweekplan',
            constraint=models.UniqueConstraint(fields=('organization', 'owner', 'week_start'), name='sched_member_week_unique'),
        ),
        migrations.AddConstraint(
            model_name='timetablerecognitionjob',
            constraint=models.UniqueConstraint(fields=('timetable_import', 'input_revision'), name='sched_job_revision_unique'),
        ),
        migrations.AddIndex(
            model_name='workschedulecell',
            index=models.Index(fields=['organization', 'date', 'effective_status'], name='sched_board_lookup'),
        ),
        migrations.AddConstraint(
            model_name='workschedulecell',
            constraint=models.UniqueConstraint(fields=('organization', 'owner', 'date', 'period'), name='sched_cell_unique'),
        ),
    ]
