import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");

const sources = {
  "/": { file: "index.html", type: "text/html; charset=utf-8" },
  "/index.html": { file: "index.html", type: "text/html; charset=utf-8" },
  "/styles.css": { file: "styles.css", type: "text/css; charset=utf-8" },
  "/app.js": { file: "app.js", type: "text/javascript; charset=utf-8" },
  "/team.js": { file: "team.js", type: "text/javascript; charset=utf-8" },
  "/runtime-config.js": { file: "runtime-config.js", type: "text/javascript; charset=utf-8" },
  "/assets/og-dongbo-crossborder.png": {
    file: "assets/og-dongbo-crossborder.png",
    type: "image/png",
    encoding: "base64",
  },
  "/monitoring-targets.json": {
    file: "monitoring-targets.json",
    type: "application/json; charset=utf-8",
  },
};

const routes = {};
for (const [pathname, source] of Object.entries(sources)) {
  const binary = source.encoding === "base64";
  routes[pathname] = {
    body: binary
      ? (await readFile(resolve(root, source.file))).toString("base64")
      : await readFile(resolve(root, source.file), "utf8"),
    type: source.type,
    encoding: source.encoding || "utf8",
  };
}

const worker = `// Generated by scripts/build-site.mjs. Do not edit this file directly.
const ROUTES = ${JSON.stringify(routes)};

function securityHeaders(contentType) {
  return {
    "content-type": contentType,
    "x-content-type-options": "nosniff",
    "referrer-policy": "strict-origin-when-cross-origin",
    "x-frame-options": "SAMEORIGIN",
    "cache-control": contentType.startsWith("text/html")
      ? "no-cache"
      : "public, max-age=300",
  };
}

function responseBody(route) {
  if (route.encoding !== "base64") return route.body;

  const binary = atob(route.body);
  return Uint8Array.from(binary, (character) => character.charCodeAt(0));
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const route = ROUTES[url.pathname];

    if (!route) {
      return new Response("Not Found", {
        status: 404,
        headers: securityHeaders("text/plain; charset=utf-8"),
      });
    }

    return new Response(request.method === "HEAD" ? null : responseBody(route), {
      status: 200,
      headers: securityHeaders(route.type),
    });
  },
};
`;

await rm(dist, { recursive: true, force: true });
await mkdir(resolve(dist, "server"), { recursive: true });
await writeFile(resolve(dist, "server", "index.js"), worker, "utf8");

console.log("Built dist/server/index.js");
